pipeline {
    agent any 
     
    stages {
        stage('Compile stage') {
            steps {
              withMaven(maven : 'maven_3_5_3') {
                sh 'mvn clean compile'
               }
             }
          }

         stage('Test') {
            steps {
                withMaven(maven : 'maven_3_5_3') {
                sh 'mvn test'
               }
             }
          }

        stage('Deploy') {
            steps {
                withMaven(maven : 'maven_3_5_3') {
                sh 'mvn deploy'
               }
             }
          }
      }
    }
